/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Jarvis' at '11/14/16 6:24 PM' with Gradle 2.14.1
 *
 * @author Jarvis, @date 11/14/16 6:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
